[package]
name = "gfx_engine"
version = "0.1.0"
authors = ["Mikko Ala-Louko <mikko.alalouko@gmail.com>"]

[dependencies]
sfml = "*"
nalgebra = '*'
libc = "*"
obj-rs = "0.5"

[lib]
name = "renderer"
path = "src/lib.rs"

[[bin]]
name = "gfx_test_app"
path = "src/main.rs"